version: '3'
services:
  web:
    container_name: 'afalunchrestapi'
    image: 'afalunchrestapi'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - 'postgres'

    links:
    - postgres

  postgres:
    ports:
      - '5432:5432'
    container_name: postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - 'postgresql-volume:/var/lib/postgresql/data'
    image: 'postgres:10.4'


volumes:
  postgresql-volume:

